<script lang="ts">
	import { page } from '$app/state';

	let { data } = $props();

	const pipeline = $derived(data.pipeline);
	const schema = $derived(data.schema);

	// Selected port detail panel
	let selectedPort = $state<{
		stepName: string;
		portName: string;
		direction: 'input' | 'output';
		portSchema: Record<string, unknown> | null;
		mimeTypes: string[];
	} | null>(null);

	// Copied feedback state
	let copiedKey = $state<string | null>(null);

	function showCopied(key: string) {
		copiedKey = key;
		setTimeout(() => {
			copiedKey = null;
		}, 1500);
	}

	// TS type generation helpers
	function jsonTypeToTs(jsonType: string): string {
		switch (jsonType) {
			case 'string':
				return 'string';
			case 'number':
			case 'integer':
				return 'number';
			case 'boolean':
				return 'boolean';
			case 'array':
				return 'unknown[]';
			case 'object':
				return 'Record<string, unknown>';
			default:
				return 'unknown';
		}
	}

	function schemaToTypeScript(name: string, portSchema: Record<string, unknown>): string {
		if (portSchema.type === 'object' && portSchema.properties) {
			const props = portSchema.properties as Record<string, { type: string; description?: string }>;
			const fields = Object.entries(props).map(([key, val]) => {
				const tsType = jsonTypeToTs(val.type);
				const comment = val.description ? ` // ${val.description}` : '';
				return `  ${key}: ${tsType};${comment}`;
			});
			return `export interface ${name} {\n${fields.join('\n')}\n}`;
		}
		return `export type ${name} = unknown;`;
	}

	function pascalCase(str: string): string {
		return str
			.split(/[\s_-]+/)
			.map((w) => w.charAt(0).toUpperCase() + w.slice(1))
			.join('');
	}

	interface PortDef {
		name: string;
		description: string;
		mimeTypes: string[];
		required: boolean;
		schema?: Record<string, unknown>;
	}

	interface StepDef {
		nodeId: string;
		adapterName: string;
		category: string;
		inputPorts: PortDef[];
		outputPorts: PortDef[];
	}

	// Build steps from pipeline data (nodes with adapter info)
	const steps = $derived((): StepDef[] => {
		if (!pipeline?.nodes) return [];
		return pipeline.nodes
			.filter((n: { adapter: unknown }) => n.adapter !== null)
			.map((n: {
				id: string;
				label: string;
				adapter: {
					name: string;
					category: string;
					inputPorts: PortDef[];
					outputPorts: PortDef[];
				};
			}) => ({
				nodeId: n.id,
				adapterName: n.adapter.name,
				category: n.adapter.category,
				inputPorts: n.adapter.inputPorts,
				outputPorts: n.adapter.outputPorts
			}));
	});

	// Generate all TypeScript interfaces
	function generateTypeScript(): string {
		const stepsData = steps();
		if (stepsData.length === 0) return '// No steps defined in this pipeline.\n';

		const interfaces: string[] = [];
		const outputTypeEntries: string[] = [];

		for (const step of stepsData) {
			const baseName = pascalCase(step.adapterName);

			for (const port of step.outputPorts) {
				const ifaceName = `${baseName}${pascalCase(port.name)}Output`;
				if (port.schema) {
					interfaces.push(schemaToTypeScript(ifaceName, port.schema));
				} else {
					interfaces.push(`export type ${ifaceName} = unknown; // mime: ${port.mimeTypes.join(', ')}`);
				}
				outputTypeEntries.push(`  ${port.name}: ${ifaceName};`);
			}
		}

		const aggregated =
			outputTypeEntries.length > 0
				? `\nexport interface PipelineOutputs {\n${outputTypeEntries.join('\n')}\n}`
				: '';

		return `// Generated by Artifactory Schema Explorer\n// Pipeline: ${pipeline?.name ?? 'unknown'}\n\n${interfaces.join('\n\n')}${aggregated}\n`;
	}

	// Generate JSON schema object
	function generateJsonSchema(): string {
		const stepsData = steps();
		const schemaObj: Record<string, unknown> = {
			$schema: 'https://json-schema.org/draft/07/schema#',
			title: pipeline?.name ?? 'Pipeline',
			type: 'object',
			properties: {}
		};

		const props = schemaObj.properties as Record<string, unknown>;

		for (const step of stepsData) {
			props[step.adapterName] = {
				type: 'object',
				properties: {
					inputs: {
						type: 'object',
						properties: Object.fromEntries(
							step.inputPorts.map((p) => [p.name, p.schema ?? { type: 'unknown' }])
						)
					},
					outputs: {
						type: 'object',
						properties: Object.fromEntries(
							step.outputPorts.map((p) => [p.name, p.schema ?? { type: 'unknown' }])
						)
					}
				}
			};
		}

		return JSON.stringify(schemaObj, null, 2);
	}

	async function copyToClipboard(text: string, key: string) {
		await navigator.clipboard.writeText(text);
		showCopied(key);
	}

	function downloadFile(filename: string, content: string) {
		const blob = new Blob([content], { type: 'text/plain' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = filename;
		a.click();
		URL.revokeObjectURL(url);
	}

	function handleCopyTs() {
		copyToClipboard(generateTypeScript(), 'ts');
	}

	function handleDownloadTs() {
		const safeName = (pipeline?.name ?? 'pipeline').replace(/\s+/g, '-').toLowerCase();
		downloadFile(`${safeName}-types.ts`, generateTypeScript());
	}

	function handleCopyJson() {
		copyToClipboard(generateJsonSchema(), 'json');
	}

	function selectPort(
		step: StepDef,
		port: PortDef,
		direction: 'input' | 'output'
	) {
		const isSame =
			selectedPort?.stepName === step.adapterName &&
			selectedPort?.portName === port.name &&
			selectedPort?.direction === direction;

		if (isSame) {
			selectedPort = null;
		} else {
			selectedPort = {
				stepName: step.adapterName,
				portName: port.name,
				direction,
				portSchema: port.schema ?? null,
				mimeTypes: port.mimeTypes
			};
		}
	}

	function isSelectedPort(step: StepDef, port: PortDef, direction: 'input' | 'output'): boolean {
		return (
			selectedPort?.stepName === step.adapterName &&
			selectedPort?.portName === port.name &&
			selectedPort?.direction === direction
		);
	}

	function getMimeColor(mimeType: string): string {
		if (mimeType.startsWith('image/')) return 'image';
		if (mimeType.startsWith('text/')) return 'text';
		if (mimeType.startsWith('model/') || mimeType.includes('3d')) return 'model';
		if (mimeType.startsWith('audio/')) return 'audio';
		if (mimeType.startsWith('video/')) return 'video';
		if (mimeType.includes('json') || mimeType.includes('xml')) return 'structured';
		return 'any';
	}

	function getCategoryVar(category: string): string {
		const cats: Record<string, string> = {
			source: 'cat-source',
			generator: 'cat-generator',
			transformer: 'cat-transformer',
			analyzer: 'cat-analyzer',
			sink: 'cat-sink'
		};
		return cats[category] ?? 'cat-source';
	}
</script>

<div class="schema-page">
	<!-- Header -->
	<header class="page-header">
		<div class="header-left">
			<nav class="breadcrumb" aria-label="Breadcrumb">
				<a href="/pipelines" class="crumb-link">Pipelines</a>
				<span class="crumb-sep" aria-hidden="true">/</span>
				{#if pipeline}
					<a href="/pipelines/{page.params.id}" class="crumb-link">{pipeline.name}</a>
				{:else}
					<span class="crumb-item">Pipeline</span>
				{/if}
				<span class="crumb-sep" aria-hidden="true">/</span>
				<span class="crumb-item crumb-current">Schema</span>
			</nav>

			<div class="header-tabs">
				<a href="/pipelines/{page.params.id}" class="tab-link">Editor</a>
				<a href="/pipelines/{page.params.id}/runs" class="tab-link">Runs</a>
				<a href="/pipelines/{page.params.id}/schema" class="tab-link tab-link--active" aria-current="page">Schema</a>
				<a href="/pipelines/{page.params.id}/settings" class="tab-link">Settings</a>
			</div>
		</div>

		<div class="header-right">
			<button
				class="export-btn"
				onclick={handleCopyTs}
				title="Copy TypeScript interface declarations to clipboard"
			>
				{#if copiedKey === 'ts'}
					<svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
						<path d="M2 7l3.5 3.5L12 3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
					</svg>
					Copied!
				{:else}
					<svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
						<rect x="4" y="1" width="9" height="9" rx="1" stroke="currentColor" stroke-width="1.25"/>
						<path d="M1 4v8a1 1 0 001 1h8" stroke="currentColor" stroke-width="1.25" stroke-linecap="round"/>
					</svg>
					Copy as TypeScript
				{/if}
			</button>

			<button
				class="export-btn"
				onclick={handleDownloadTs}
				title="Download TypeScript declarations as a .ts file"
			>
				<svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
					<path d="M7 1v7M4 6l3 3 3-3" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>
					<path d="M2 11h10" stroke="currentColor" stroke-width="1.25" stroke-linecap="round"/>
				</svg>
				Download .ts
			</button>

			<button
				class="export-btn"
				onclick={handleCopyJson}
				title="Copy JSON Schema to clipboard"
			>
				{#if copiedKey === 'json'}
					<svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
						<path d="M2 7l3.5 3.5L12 3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
					</svg>
					Copied!
				{:else}
					<svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
						<rect x="4" y="1" width="9" height="9" rx="1" stroke="currentColor" stroke-width="1.25"/>
						<path d="M1 4v8a1 1 0 001 1h8" stroke="currentColor" stroke-width="1.25" stroke-linecap="round"/>
					</svg>
					Copy JSON Schema
				{/if}
			</button>
		</div>
	</header>

	<!-- Body -->
	<div class="page-body">
		{#if !pipeline}
			<div class="empty-state">
				<p class="empty-msg">Pipeline not found.</p>
			</div>
		{:else if steps().length === 0}
			<div class="empty-state">
				<p class="empty-msg">No steps in this pipeline yet. Add adapters in the Editor to see the schema.</p>
			</div>
		{:else}
			<div class="schema-layout">
				<!-- Step cards -->
				<div class="steps-column">
					{#each steps() as step (step.nodeId)}
						{@const catVar = getCategoryVar(step.category)}
						<div class="step-card" style="border-left-color: var(--color-{catVar});">
							<!-- Step header -->
							<div class="step-header">
								<span class="step-name">{step.adapterName}</span>
								<span
									class="category-badge"
									style="background-color: var(--color-{catVar}-subtle); color: var(--color-{catVar});"
								>
									{step.category}
								</span>
							</div>

							<!-- Ports -->
							<div class="ports-grid">
								<!-- Inputs -->
								{#if step.inputPorts.length > 0}
									<div class="ports-section">
										<p class="ports-label">Inputs</p>
										<ul class="port-list" role="list">
											{#each step.inputPorts as port (port.name)}
												<li>
													<button
														class="port-row"
														class:port-row--selected={isSelectedPort(step, port, 'input')}
														onclick={() => selectPort(step, port, 'input')}
														aria-pressed={isSelectedPort(step, port, 'input')}
													>
														<span class="port-name">{port.name}</span>
														<div class="mime-pills">
															{#each port.mimeTypes as mime}
																{@const colorKey = getMimeColor(mime)}
																<span
																	class="mime-pill"
																	style="background-color: var(--color-port-{colorKey}-subtle); color: var(--color-port-{colorKey});"
																>
																	{mime}
																</span>
															{/each}
															{#if port.schema}
																<span class="schema-indicator" title="Has schema">schema</span>
															{/if}
														</div>
													</button>
												</li>
											{/each}
										</ul>
									</div>
								{/if}

								<!-- Outputs -->
								{#if step.outputPorts.length > 0}
									<div class="ports-section">
										<p class="ports-label">Outputs</p>
										<ul class="port-list" role="list">
											{#each step.outputPorts as port (port.name)}
												<li>
													<button
														class="port-row"
														class:port-row--selected={isSelectedPort(step, port, 'output')}
														onclick={() => selectPort(step, port, 'output')}
														aria-pressed={isSelectedPort(step, port, 'output')}
													>
														<span class="port-name">{port.name}</span>
														<div class="mime-pills">
															{#each port.mimeTypes as mime}
																{@const colorKey = getMimeColor(mime)}
																<span
																	class="mime-pill"
																	style="background-color: var(--color-port-{colorKey}-subtle); color: var(--color-port-{colorKey});"
																>
																	{mime}
																</span>
															{/each}
															{#if port.schema}
																<span class="schema-indicator" title="Has schema">schema</span>
															{/if}
														</div>
													</button>
												</li>
											{/each}
										</ul>
									</div>
								{/if}
							</div>
						</div>
					{/each}

					<!-- Schema API notice when schema endpoint missing -->
					{#if schema === null}
						<div class="api-notice">
							<p>Schema data not available. Add the schema endpoint to enable this feature.</p>
						</div>
					{/if}
				</div>

				<!-- Port detail panel -->
				{#if selectedPort}
					<aside class="detail-panel" aria-label="Port detail">
						<div class="detail-header">
							<div class="detail-title-row">
								<span class="detail-direction-badge" class:detail-direction-badge--input={selectedPort.direction === 'input'}>
									{selectedPort.direction}
								</span>
								<h2 class="detail-title">{selectedPort.stepName} / {selectedPort.portName}</h2>
							</div>
							<button
								class="detail-close"
								onclick={() => { selectedPort = null; }}
								aria-label="Close detail panel"
							>
								<svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
									<path d="M2 2l10 10M12 2L2 12" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
								</svg>
							</button>
						</div>

						<div class="detail-body">
							<!-- Mime types -->
							<div class="detail-section">
								<p class="detail-section-label">Accepted types</p>
								<div class="mime-pills">
									{#each selectedPort.mimeTypes as mime}
										{@const colorKey = getMimeColor(mime)}
										<span
											class="mime-pill"
											style="background-color: var(--color-port-{colorKey}-subtle); color: var(--color-port-{colorKey});"
										>
											{mime}
										</span>
									{/each}
								</div>
							</div>

							<!-- Schema -->
							{#if selectedPort.portSchema}
								<div class="detail-section">
									<p class="detail-section-label">JSON Schema</p>
									<pre class="schema-code">{JSON.stringify(selectedPort.portSchema, null, 2)}</pre>
								</div>

								<div class="detail-section">
									<p class="detail-section-label">TypeScript</p>
									<pre class="schema-code">{schemaToTypeScript(
										pascalCase(selectedPort.stepName) + pascalCase(selectedPort.portName) + (selectedPort.direction === 'output' ? 'Output' : 'Input'),
										selectedPort.portSchema
									)}</pre>
								</div>
							{:else}
								<div class="detail-section">
									<p class="detail-no-schema">No schema defined for this port. The port accepts the listed mime types with no additional structural constraints.</p>
								</div>
							{/if}
						</div>
					</aside>
				{/if}
			</div>
		{/if}
	</div>
</div>

<style>
	.schema-page {
		display: flex;
		flex-direction: column;
		height: 100%;
		overflow: hidden;
		background-color: var(--color-bg-primary);
	}

	/* Header */
	.page-header {
		display: flex;
		align-items: flex-end;
		justify-content: space-between;
		padding: var(--spacing-3) var(--spacing-6) 0;
		background-color: var(--color-bg-secondary);
		border-bottom: 1px solid var(--color-border-primary);
		flex-shrink: 0;
		gap: var(--spacing-4);
	}

	.header-left {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-2);
		min-width: 0;
	}

	.header-right {
		display: flex;
		align-items: center;
		gap: var(--spacing-2);
		padding-bottom: var(--spacing-3);
		flex-shrink: 0;
	}

	/* Breadcrumb */
	.breadcrumb {
		display: flex;
		align-items: center;
		gap: var(--spacing-1);
		font-size: 0.8125rem;
	}

	.crumb-link {
		color: var(--color-text-secondary);
		text-decoration: none;
		transition: color var(--duration-fast) var(--easing-default);
	}

	.crumb-link:hover {
		color: var(--color-text-primary);
	}

	.crumb-link:focus-visible {
		outline: 2px solid var(--color-border-focus);
		outline-offset: 2px;
		border-radius: var(--radius-sm);
	}

	.crumb-sep {
		color: var(--color-text-muted);
	}

	.crumb-item {
		color: var(--color-text-secondary);
	}

	.crumb-current {
		color: var(--color-text-primary);
		font-weight: 500;
	}

	/* Tabs */
	.header-tabs {
		display: flex;
		gap: 0;
	}

	.tab-link {
		display: inline-flex;
		align-items: center;
		padding: var(--spacing-2) var(--spacing-3);
		font-size: 0.8125rem;
		font-weight: 500;
		color: var(--color-text-secondary);
		text-decoration: none;
		border-bottom: 2px solid transparent;
		transition: color var(--duration-fast) var(--easing-default),
			border-color var(--duration-fast) var(--easing-default);
	}

	.tab-link:hover {
		color: var(--color-text-primary);
	}

	.tab-link--active {
		color: var(--color-text-primary);
		border-bottom-color: var(--color-border-focus);
	}

	.tab-link:focus-visible {
		outline: 2px solid var(--color-border-focus);
		outline-offset: -2px;
		border-radius: var(--radius-sm) var(--radius-sm) 0 0;
	}

	/* Export buttons */
	.export-btn {
		display: inline-flex;
		align-items: center;
		gap: var(--spacing-1);
		height: 30px;
		padding: 0 var(--spacing-3);
		border: 1px solid var(--color-border-primary);
		border-radius: var(--radius-md);
		background-color: var(--color-bg-surface);
		color: var(--color-text-secondary);
		font-size: 0.8125rem;
		font-weight: 500;
		cursor: pointer;
		white-space: nowrap;
		transition: background-color var(--duration-fast) var(--easing-default),
			color var(--duration-fast) var(--easing-default),
			border-color var(--duration-fast) var(--easing-default);
	}

	.export-btn:hover {
		background-color: var(--color-bg-surface-hover);
		color: var(--color-text-primary);
	}

	.export-btn:focus-visible {
		outline: 2px solid var(--color-border-focus);
		outline-offset: 2px;
	}

	/* Body */
	.page-body {
		flex: 1;
		overflow: auto;
		padding: var(--spacing-6);
	}

	.empty-state {
		display: flex;
		align-items: center;
		justify-content: center;
		height: 100%;
		min-height: 200px;
	}

	.empty-msg {
		font-size: 0.875rem;
		color: var(--color-text-muted);
		background-color: var(--color-bg-surface);
		padding: var(--spacing-3) var(--spacing-4);
		border-radius: var(--radius-md);
		border: 1px solid var(--color-border-subtle);
		text-align: center;
		max-width: 480px;
	}

	/* Schema layout */
	.schema-layout {
		display: flex;
		gap: var(--spacing-6);
		align-items: flex-start;
		min-height: 100%;
	}

	/* Steps column */
	.steps-column {
		flex: 1;
		display: flex;
		flex-direction: column;
		gap: var(--spacing-4);
		min-width: 0;
	}

	/* Step card */
	.step-card {
		background-color: var(--color-bg-surface);
		border: 1px solid var(--color-border-primary);
		border-left-width: 3px;
		border-radius: var(--radius-md);
		overflow: hidden;
		box-shadow: var(--shadow-sm);
	}

	.step-header {
		display: flex;
		align-items: center;
		gap: var(--spacing-2);
		padding: var(--spacing-3) var(--spacing-4);
		border-bottom: 1px solid var(--color-border-subtle);
	}

	.step-name {
		font-size: 0.9375rem;
		font-weight: 600;
		color: var(--color-text-primary);
		flex: 1;
	}

	.category-badge {
		font-size: 0.6875rem;
		font-weight: 600;
		padding: 2px 8px;
		border-radius: var(--radius-full);
		text-transform: uppercase;
		letter-spacing: 0.05em;
		flex-shrink: 0;
	}

	/* Ports grid */
	.ports-grid {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 0;
	}

	.ports-section {
		padding: var(--spacing-3) var(--spacing-4);
	}

	.ports-section + .ports-section {
		border-left: 1px solid var(--color-border-subtle);
	}

	.ports-label {
		font-size: 0.6875rem;
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.06em;
		color: var(--color-text-muted);
		margin: 0 0 var(--spacing-2) 0;
	}

	.port-list {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-1);
		margin: 0;
		padding: 0;
		list-style: none;
	}

	.port-row {
		display: flex;
		align-items: flex-start;
		gap: var(--spacing-2);
		width: 100%;
		padding: var(--spacing-2) var(--spacing-2);
		border: 1px solid transparent;
		border-radius: var(--radius-sm);
		background: none;
		cursor: pointer;
		text-align: left;
		flex-wrap: wrap;
		transition: background-color var(--duration-fast) var(--easing-default),
			border-color var(--duration-fast) var(--easing-default);
	}

	.port-row:hover {
		background-color: var(--color-bg-surface-hover);
	}

	.port-row--selected {
		background-color: var(--color-bg-surface-selected);
		border-color: var(--color-border-focus);
	}

	.port-row:focus-visible {
		outline: 2px solid var(--color-border-focus);
		outline-offset: 1px;
	}

	.port-name {
		font-size: 0.8125rem;
		font-weight: 500;
		color: var(--color-text-primary);
		font-family: var(--font-family-mono);
		flex-shrink: 0;
	}

	.mime-pills {
		display: flex;
		flex-wrap: wrap;
		gap: var(--spacing-1);
		align-items: center;
	}

	.mime-pill {
		font-size: 0.6875rem;
		font-weight: 500;
		padding: 1px 6px;
		border-radius: var(--radius-sm);
		font-family: var(--font-family-mono);
		white-space: nowrap;
	}

	.schema-indicator {
		font-size: 0.625rem;
		font-weight: 600;
		padding: 1px 5px;
		border-radius: var(--radius-sm);
		text-transform: uppercase;
		letter-spacing: 0.04em;
		background-color: var(--color-bg-surface-selected);
		color: var(--color-text-muted);
	}

	/* API notice */
	.api-notice {
		background-color: var(--color-bg-surface);
		border: 1px solid var(--color-border-subtle);
		border-radius: var(--radius-md);
		padding: var(--spacing-3) var(--spacing-4);
	}

	.api-notice p {
		margin: 0;
		font-size: 0.8125rem;
		color: var(--color-text-muted);
	}

	/* Detail panel */
	.detail-panel {
		width: 340px;
		flex-shrink: 0;
		background-color: var(--color-bg-surface);
		border: 1px solid var(--color-border-primary);
		border-radius: var(--radius-lg);
		box-shadow: var(--shadow-md);
		overflow: hidden;
		position: sticky;
		top: 0;
	}

	.detail-header {
		display: flex;
		align-items: flex-start;
		gap: var(--spacing-2);
		padding: var(--spacing-3) var(--spacing-4);
		border-bottom: 1px solid var(--color-border-subtle);
	}

	.detail-title-row {
		display: flex;
		align-items: center;
		gap: var(--spacing-2);
		flex: 1;
		min-width: 0;
		flex-wrap: wrap;
	}

	.detail-direction-badge {
		font-size: 0.625rem;
		font-weight: 700;
		padding: 2px 6px;
		border-radius: var(--radius-sm);
		text-transform: uppercase;
		letter-spacing: 0.06em;
		background-color: var(--color-cat-generator-subtle);
		color: var(--color-cat-generator);
		flex-shrink: 0;
	}

	.detail-direction-badge--input {
		background-color: var(--color-cat-transformer-subtle);
		color: var(--color-cat-transformer);
	}

	.detail-title {
		font-size: 0.875rem;
		font-weight: 600;
		color: var(--color-text-primary);
		margin: 0;
		font-family: var(--font-family-mono);
		word-break: break-all;
	}

	.detail-close {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 24px;
		height: 24px;
		flex-shrink: 0;
		border: none;
		border-radius: var(--radius-sm);
		background: none;
		cursor: pointer;
		color: var(--color-text-muted);
		transition: background-color var(--duration-fast) var(--easing-default),
			color var(--duration-fast) var(--easing-default);
	}

	.detail-close:hover {
		background-color: var(--color-bg-surface-hover);
		color: var(--color-text-primary);
	}

	.detail-close:focus-visible {
		outline: 2px solid var(--color-border-focus);
		outline-offset: 2px;
	}

	.detail-body {
		padding: var(--spacing-4);
		display: flex;
		flex-direction: column;
		gap: var(--spacing-4);
		max-height: calc(100vh - 200px);
		overflow-y: auto;
	}

	.detail-section {
		display: flex;
		flex-direction: column;
		gap: var(--spacing-2);
	}

	.detail-section-label {
		font-size: 0.6875rem;
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.06em;
		color: var(--color-text-muted);
		margin: 0;
	}

	.schema-code {
		font-family: var(--font-family-mono);
		font-size: 0.75rem;
		line-height: 1.6;
		color: var(--color-text-primary);
		background-color: var(--color-bg-secondary);
		border: 1px solid var(--color-border-subtle);
		border-radius: var(--radius-sm);
		padding: var(--spacing-3);
		margin: 0;
		overflow-x: auto;
		white-space: pre;
	}

	.detail-no-schema {
		font-size: 0.8125rem;
		color: var(--color-text-muted);
		margin: 0;
		line-height: 1.5;
	}
</style>
